name: linkan

default-extensions:
  - DerivingStrategies
  - OverloadedStrings
  - PatternSynonyms
  - ViewPatterns
  - BlockArguments
  - ConstraintKinds
  - ImplicitParams
  - LambdaCase
  - OverloadedStrings
  - ParallelListComp
  - PatternSynonyms
  - RankNTypes
  - RecursiveDo
  - ScopedTypeVariables
  - ViewPatterns
  - DeriveAnyClass
  - ImportQualifiedPost

dependencies:
  - base >= 4.14.2.0
  - containers
  - megaparsec
  - mtl
  - haskeline
  - exceptions

library:
  source-dirs: src
